### ISSUE TITLE
Did you authorize other people to use this repository?

### ISSUE THREAD

**Issue by xuewei4d** [KarlZhu-SE/ark-funds-monitor#105]
Hi,

This is an awesome project. I saw some websites using this repo. I am wondering did you authorize other people? Do you have any licenses to use your project?

Best,

**Comment by KarlZhu-SE** [comment]
Hi,
Thank you for reaching out to me.
This repo is using MIT license. 
I have not seen any other websites using my code.
Could you please provide me these websites?

If they are monetizing it, I would like to switch to a more strict license.

Thanks,
Karl

**Comment by haotongye** [comment]
https://www.youtube.com/watch?v=oT-lw46Ug0I
https://like-paris.com/ark-funds-monitor/public/

**Comment by xuewei4d** [comment]
Sadly, they also run google ads on their website using your project.

**Comment by KarlZhu-SE** [comment]
Thanks. @haotongye @xuewei4d 
I already switched to GPL.

**Comment by ouiigo** [comment]
hi KarlZhu, could you please contact me by ouiigo.xc@gmail.com?  I am managing the website like-paris.com and would like to discuss with you for the potiential cooperations. Thanks
