### ISSUE TITLE
Permission to use your Monitor

### ISSUE THREAD

**Issue by iqchong** [KarlZhu-SE/ark-funds-monitor#108]
dear sir, i found your ARK-funds monitor very useful and intuitive, therefore would like to ask your permission to use your monitor in our upcoming website? kindly drop me an email : iqchong@gmail.com.  Thanks a lot!

**Comment by KarlZhu-SE** [comment]
Hi,
For sure, you can use this repo. Please indicate the source and the original author on your website. Also, please follow AGPL 3.0 license and publish your source code if the website is facing the crowd.

Thanks for reaching out to me.

Best,
Karl Zhu
