### ISSUE TITLE
The transaction seem not update on Dec 17. 

### ISSUE THREAD

**Issue by XiaoruiZhu** [KarlZhu-SE/ark-funds-monitor#112]
The transaction seem not update on Dec 17. 

  | Fund | Date | Direction | Ticker | CUSIP | Company | Shares | % of ETF
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | ARKG | 12/17/2020 | Buy | RHHBY | 771195104 | ROCHE HOLDING AG | 276,156 | 0.1988
2 | ARKG | 12/17/2020 | Buy | SDGR | 80810D103 | SCHRODINGER INC/UNITED STATES | 74,834 | 0.0958
3 | ARKG | 12/17/2020 | Buy | TAK | 874060205 | TAKEDA PHARMACEUTICAL CO LTD | 207,887 | 0.0642
4 | ARKG | 12/17/2020 | Buy | REGN | 75886F107 | REGENERON PHARMACEUTICALS INC | 30,549 | 0.2486
5 | ARKG | 12/17/2020 | Buy | NVS | 66987V109 | NOVARTIS AG | 196,970 | 0.2987
6 | ARKG | 12/17/2020 | Buy | IOVA | 462260100 | IOVANCE BIOTHERAPEUTICS INC | 140,018 | 0.1057
7 | ARKG | 12/17/2020 | Buy | IONS | 462222100 | IONIS PHARMACEUTICALS INC | 152,185 | 0.1265
8 | ARKG | 12/17/2020 | Buy | INCY | 45337C102 | INCYTE CORP | 52,600 | 0.0758
9 | ARKG | 12/17/2020 | Buy | TDOC | 87918A105 | TELADOC HEALTH INC | 26,999 | 0.0856
10 | ARKG | 12/17/2020 | Buy | EXAS | 30063P105 | EXACT SCIENCES CORP | 28,099 | 0.0605
11 | ARKG | 12/17/2020 | Buy | VRTX | 92532F100 | VERTEX PHARMACEUTICALS INC | 52,000 | 0.2021
12 | ARKG | 12/17/2020 | Buy | CDXS | 192005106 | CODEXIS INC | 14,422 | 0.0046
13 | ARKG | 12/17/2020 | Buy | BLI | 084310101 | BERKELEY LIGHTS INC | 28,546 | 0.0422
14 | ARKG | 12/17/2020 | Buy | SURF | 86877M209 | SURFACE ONCOLOGY INC | 1,009,200 | 0.1401
15 | ARKG | 12/17/2020 | Sell | ARCT | 03969T109 | ARCTURUS THERAPEUTICS HOLDINGS INC | 75,216 | 0.1283
16 | ARKG | 12/17/2020 | Sell | FATE | 31189P102 | FATE THERAPEUTICS INC | 128,652 | 0.1934
17 | ARKG | 12/17/2020 | Sell | CRSP | H17182108 | CRISPR THERAPEUTICS AG | 65,448 | 0.1595
18 | ARKK | 12/17/2020 | Buy | IOVA | 462260100 | IOVANCE BIOTHERAPEUTICS INC | 348,778 | 0.0957
19 | ARKK | 12/17/2020 | Buy | U | 91332U101 | UNITY SOFTWARE INC | 80,484 | 0.0728
20 | ARKK | 12/17/2020 | Sell | WORK | 83088V102 | SLACK TECHNOLOGIES INC | 7,472 | 0.0019
21 | ARKK | 12/17/2020 | Sell | XONE | 302104104 | EXONE CO/THE | 53,114 | 0.0038
22 | ARKQ | 12/17/2020 | Buy | BIDU | 056752108 | BAIDU INC | 18,354 | 0.2482
23 | ARKQ | 12/17/2020 | Buy | KMTUY | 500458401 | KOMATSU LTD | 8,100 | 0.0157

**Comment by KarlZhu-SE** [comment]
Hi Xiaorui,
May I know which section is missing 12/17 trans?
I checked Transaction Table, it is up to date.
![image](https://user-images.githubusercontent.com/28239241/102680655-3544ef80-4188-11eb-87b9-46049313a022.png)

**Comment by XiaoruiZhu** [comment]
> Hi Xiaorui,
> May I know which section is missing 12/17 trans?
> I checked Transaction Table, it is up to date.
> ![image](https://user-images.githubusercontent.com/28239241/102680655-3544ef80-4188-11eb-87b9-46049313a022.png)

Thanks for the reply. I checked the transactions on 12/18 but didnot see them. Now they are there. I guess it may just due to the time you update the all transactions. Thanks a lot. Very good product. 

BTW, I saw the "https://ark.alien-tomato.com/" seems using the same source, right?
