### ISSUE TITLE
Nana is using your code without replacing the Finnhub API token

### ISSUE THREAD

**Issue by goodman-capu** [KarlZhu-SE/ark-funds-monitor#119]
I just found a YouTuber who copied your code without modifying Finnhub token:

https://like-paris.com/ark-funds-monitor/public/

Just monitor the network traffic and we can find that she's using the same API token.

I suggest you contact the author, or replace the token on your end. Her website has higher traffic and might impact yours (429). I noticed this because when her website is down because of high traffic, I tried to use yours as alternative, but it's also down.

Thanks for making the amazing tool BTW!

**Comment by KarlZhu-SE** [comment]
Hi @goodman-capu,
Thank you! I just asked them to change the token on their end.

**Comment by goodman-capu** [comment]
Awesome!
