### ISSUE TITLE
看了番茄的视频，发现您的项目很有意思哈，但有个问题想请教您一下

### ISSUE THREAD

**Issue by jing-ge-star** [KarlZhu-SE/ark-funds-monitor#147]
我发现，咱这个项目中的交易记录，好像不是很完整哈？
我简单对比了一下，咱们的数据基本是来自Ark邮件中的（这个只是Ark交易的一部分）：
  https://github.com/KarlZhu-SE/ark-funds-monitor/blob/master/src/rawData/mergedData.json
但是番茄官网中的交易记录更完整，不知道从那里可以获得呢？您有研究或者有更好的建议吗？
期待您的再次分享，谢谢

**Comment by KarlZhu-SE** [comment]
你好，
他应该是通过每天比较ark持仓，计算持仓变化来得出的。这部分数据需要每天比较，持续积累。

Best,
Karl Zhu
