### ISSUE TITLE
Add support for `CTRU`

### ISSUE THREAD

**Issue by MichaelDeBoey** [KarlZhu-SE/ark-funds-monitor#283]
https://ark-funds.com/funds/ctru

**Comment by MichaelDeBoey** [comment]
@KarlZhu-SE 
- https://ark-funds.com/wp-content/uploads/funds-etf-pdf/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.pdf
- https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.csv

**Comment by KarlZhu-SE** [comment]
Hi @MichaelDeBoey,
Thanks for reaching out to me.
I believe CTRU is a passive ETF. so prefer not to include it.
