### ISSUE TITLE
Init issue?

### ISSUE THREAD

**Issue by paulhchoi** [KarlZhu-SE/ark-funds-monitor#67]
Hey Karl!

Love what you're doing here -- thought of creating a small monitoring app myself, before I saw that you've already begun one. I'd like to check out your app and run it locally but I'm running into issues doing so. I've downloaded your repo, ran `npm install`, and then `npm start`.

After this, I'm just getting a blank white browser on "http://localhost:3000/ark-funds-monitor", and my console flashes:
```
Starting the development server...

Parsed 929 transactions
Wrote data to ark-transactions-data/daily-summary/lastest.json
Wrote data to src/rawData/mergedData.json
Pre-build tasks: 1.463s
```

before being overwritten by
```
Failed to compile.
```

Is there more to do other than those two cmds? Thanks for your help!

**Comment by KarlZhu-SE** [comment]
Hi Paul,
Thanks for interesting in this repo!
Basically, nothing more than npm i & npm run start. You may try to refresh the blank page after initial loading(that is what I used to do).

For the compilation error, I am not sure about the details. If the console does not give you any more info, try switch to karl-wip branch and host again. It should be fine since I run on this branch on a daily basis.

Best,
Karl Zhu

**Comment by paulhchoi** [comment]
Oh interesting, refreshing the page seems to show this error:
```
Failed to compile

./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

This error occurred during the build time and cannot be dismissed.
```

The error seems present in your `karl-wip` branch as well. Seeing as how this works for you, there must be some config error with sass on my machine. I'll try and figure something out and will post back on here if/when I find the fix. Much appreciated! 👍🏽
