### ISSUE TITLE
Changing data source?

### ISSUE THREAD

**Issue by et291508** [KarlZhu-SE/ark-funds-monitor#87]
It seems like the transaction data were extracted from ARK subscription mail. However there are some records can only be observed by retrieving the funds holding list day by day and comparing between two consecutive trading date, is it possible that changing the data source to that and labeling the trading operation like arktrack site do (https://www.arktrack.com/)

**Comment by KarlZhu-SE** [comment]
Hi,
It is a good idea to get data from funds holding list.
considering the website you mentioned is doing a great job with it, I would like to add more features based on the holding list maybe Pie chart/simple prediction, at the same time, keep using current data source for current features.

Thanks a lot!

Best,
Karl Zhu
