### ISSUE TITLE
Trading data from 11/11/2019 - 11/12/2019 

### ISSUE THREAD

**Issue by Allen1212** [KarlZhu-SE/ark-funds-monitor#90]
Hey Karl,

You did an awesome job. I just did another ARK tracing project last weekend. I found the trading data from 11/12/2019 to 11/11/2020. You can download from [here](https://ark-invest.com/wp-content/trades/ARK_Trades.pdf?__cf_chl_jschl_tk__=3df0c3113c2398c83513970a9610675c9a5e07cc-1606755951-0-AfLFthdatP3ePqRw5M-VMx1jIzoAuRxroeI5UVVZtzYlyN8yvP2oLMyMUEYv7phPN3lSrVtZPkXsh88ql5HrPkuXwihIEDaiTMcFQbtEto6o1HIfChz1GuKcGaYY_qjutQEIn8St2Syr5X1joKg__q4IdrCCBdzLqyq2ldynNt1Fbyd6ZXGg5vzCQE_6xArkMbSvY95sjb3BHW9LzYTvjI7OygKgxEf2_hUMtEZLGjCkS1Z61IYoNbttHzaB7c3SbJjnYI3RcFHS6u0SVGu1VA5cKWqC2g1u0t4y2q3Msa3Y555rV1GfickHHI3t4xgdM_hNZjB7XCHzeuSOeEpPnlJfGj3yVjZIfv6dKCqzaa2j). Hope it can help your project.

**Comment by KarlZhu-SE** [comment]
Thank you, Allen!
It will help me a lot.
Really appreciate it.

Best,
Karl Zhu
